name: "Sweep Orphaned Lambda Versions"

on:
  workflow_dispatch:
    inputs:
      deployment-name:
        description: "Deployment prefix (e.g. ci-scaleto0, prod-refresh)"
        required: true
      aws-region:
        description: "AWS region"
        default: "eu-west-2"

jobs:
  sweep-lambda-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS role via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: false
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Assume AWS deployment role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Discover Lambda functions
        id: discover
        shell: bash
        env:
          PREFIX: ${{ inputs.deployment-name }}
        run: |
          set -euo pipefail

          aws lambda list-functions \
            --query "Functions[?starts_with(FunctionName, \`${PREFIX}\`)].FunctionName" \
            --output text > functions.txt

          if [ ! -s functions.txt ]; then
            echo "No Lambda functions found for prefix ${PREFIX}"
            exit 0
          fi

          echo "Found functions:"
          cat functions.txt

      - name: Sweep orphaned versions
        shell: bash
        env:
          AWS_REGION: ${{ inputs.aws-region }}
        run: |
          set -euo pipefail

          while read -r FUNCTION_NAME; do
            echo ""
            echo "Processing ${FUNCTION_NAME}"

            # Get all aliases and their versions
            mapfile -t ALIAS_VERSIONS < <(
              aws lambda list-aliases \
                --function-name "${FUNCTION_NAME}" \
                --query "Aliases[].FunctionVersion" \
                --output text
            )

            # Build protected version set
            PROTECTED_VERSIONS=()
            for v in "${ALIAS_VERSIONS[@]}"; do
              PROTECTED_VERSIONS+=("$v")
            done

            # Get all versions
            mapfile -t ALL_VERSIONS < <(
              aws lambda list-versions-by-function \
                --function-name "${FUNCTION_NAME}" \
                --query "Versions[?Version!='\$LATEST'].Version" \
                --output text
            )

            for VERSION in "${ALL_VERSIONS[@]}"; do
              # Skip protected versions
              if [[ " ${PROTECTED_VERSIONS[*]} " =~ " ${VERSION} " ]]; then
                echo "  ↳ Keeping version ${VERSION} (referenced by alias)"
                continue
              fi

              # Check for provisioned concurrency
              PC_STATUS=$(aws lambda get-provisioned-concurrency-config \
                --function-name "${FUNCTION_NAME}" \
                --qualifier "${VERSION}" \
                --query "Status" \
                --output text 2>/dev/null || echo "NONE")

              if [ "${PC_STATUS}" != "NONE" ]; then
                echo "  ↳ Skipping version ${VERSION} (PC status: ${PC_STATUS})"
                continue
              fi

              echo "  🧹 Deleting orphaned version ${VERSION}"
              aws lambda delete-function \
                --function-name "${FUNCTION_NAME}" \
                --qualifier "${VERSION}"

            done
          done < functions.txt

      - name: Summary
        run: |
          echo "Lambda version sweep completed successfully"
